modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

# 纯客户端模组：专用服务器不能装
displayTest="IGNORE_ALL_VERSION"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"

# 孖变台由 Alex's Mobs 提供
[[dependencies.${mod_id}]]
    modId="alexsmobs"
    mandatory=true
    versionRange="[1.22,)"
    ordering="AFTER"
    side="CLIENT"
